### PR TITLE
[FIX] Figures of components with index 0 get rendered now

### LINKED ISSUE #766: Figures may not render in interactive reports
### Summary
In a data set that @javiergcas is using, for some reason just one component will not render in the interactive reports. If I take a look at the figures subdirectory, the figure exists. 
Attached some images, including browser debugging console, for JS folks to look at.

### Additional Detail
Non-working component
image
Working component (all others work)
image
Debug console output
image

### Next Steps
- [ ] Figure out the source of the bug
- [ ] Patch

### PR DESCRIPTION
**Pull request by eurunuela**
Closes #766 .

Changes proposed in this pull request:

- Add console log for debugging purposes.
- Accept components with index 0 for updating figures on reports.
- Limit Bokeh version to <2.3.0.

### CODE REVIEW

**Comment by tsalo** [comment]
To be honest the diff from the auto formatting is making it hard to see what the meaningful changes were. Could you add in a couple of comments to point to the affected code?

**Review by eurunuela — COMMENTED** [review]
After sharing a couple of emails with [angharaddecates from Neurostars](https://neurostars.org/t/re-help-with-html-output-from-tedana/20197/4) we have found out that reports generated with Bokeh v2.3 or higher won't render at all. I've just added this constraint to `info.py` in `e4f1c36`.

**Comment by eurunuela** [comment]
This PR is much easier to review now. Thank you @tsalo for merging #758 .

**Review by jbteves — APPROVED** [review]
LGTM, thanks @eurunuela !

**Comment by eurunuela** [comment]
> The changes look good to me, but can you add in the dependency change to the "Changes proposed" section of the summary comment before we merge?

Done! I had completely forgotten about it, thank you @tsalo !

I'll merge once the tests pass.

**Comment by eurunuela** [comment]
I don't know what's wrong with the 3-echo test... it keeps hanging up... Given that this PR does NOT add anything that could conflict with the test, I'll merge.

**Comment by jbteves** [comment]
Hm, we just had the same thing happen with `main` for some reason...

**Comment by eurunuela** [comment]
Can someone with admin permissions merge so we can release?

**Comment by tsalo** [comment]
Sure, I'll push it through. We should open an issue about the three-echo problem though.

**Pull request merged**
