### PR TITLE
[ENH] Automatically use Nilearn's EPI mask when no explicit mask is provided

### PR DESCRIPTION
**Pull request by tsalo**
References #113.

Changes proposed in this pull request:

- When an explicit mask is not provided, use [nilearn.masking.compute_epi_mask](https://nilearn.github.io/modules/generated/nilearn.masking.compute_epi_mask.html) on the first echo to define the initial mask, which will be adjusted by `make_adaptive_mask`. The first echo should have the least dropout, and thus should produce the largest mask, but will avoid problems we've been seeing where the adaptive mask includes almost all of the voxels in the bounding box.

### CODE REVIEW

**Comment by emdupre** [comment]
I compared the artifacts for the five-echo dataset for this PR and current master -- it looks like (unsurprisingly) the mask differences are rippling down to the component level.

For example, in the [most recent master circle build](https://1852-110845855-gh.circle-artifacts.com/0/tmp/data/five-echo/TED.five-echo/comp_table_ica.txt) the first component is rejected for mid-kappa thresholding, while [with this PR](https://1893-110845855-gh.circle-artifacts.com/0/tmp/data/five-echo/TED.five-echo/comp_table_ica.txt) we see that the first component is now accepted.

Just to say explicitly: I am in favor of this change (!), but it might be something we're ready with our rationale for, either noted here or in the docs.

**Comment by tsalo** [comment]
I can definitely update the documentation in the Processing pipeline details page, the tedana_workflow documentation, and the CLI documentation.

Also, the CI run where the first component (i.e., the one with the highest Kappa) is classified as mid-Kappa seems to be from #228. That shouldn't be possible, so I'm going to dig into that over in that PR.

**Comment by emdupre** [comment]
Do you want to merge this, or do you want to wait pending investigations in #229 ?

**Comment by tsalo** [comment]
I don't think anything in #229 will tie directly into the mask, so I'd be happy to merge this now.

**Comment by emdupre** [comment]
Merging then :tada:

**Pull request merged**
