### PR TITLE
[FIX] Styling issues and make RTD build work

### LINKED ISSUE #961: RTD build is failing
### Summary

The RTD CI build is failing for new PRs (see #960).

### Additional Detail

Here's the traceback from https://readthedocs.org/projects/tedana/builds/21497932/:

```
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/tedana/envs/959/lib/python3.8/site-packages/sphinx/builders/html/__init__.py", line 1098, in handle_page
    output = self.templates.render(templatename, ctx)
  File "/home/docs/checkouts/readthedocs.org/user_builds/tedana/envs/959/lib/python3.8/site-packages/readthedocs_ext/readthedocs.py", line 181, in rtd_render
    content = old_render(template, render_context)
  File "/home/docs/checkouts/readthedocs.org/user_builds/tedana/envs/959/lib/python3.8/site-packages/sphinx/jinja2glue.py", line 196, in render
    return self.environment.get_template(template).render(context)
  File "/home/docs/checkouts/readthedocs.org/user_builds/tedana/envs/959/lib/python3.8/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/home/docs/checkouts/readthedocs.org/user_builds/tedana/envs/959/lib/python3.8/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/docs/checkouts/readthedocs.org/user_builds/tedana/envs/959/lib/python3.8/site-packages/sphinx/themes/basic/page.html", line 10, in top-level template code
    {%- extends "layout.html" %}
  File "/home/docs/checkouts/readthedocs.org/user_builds/tedana/envs/959/lib/python3.8/site-packages/sphinx_rtd_theme/layout.html", line 67, in top-level template code
    <link rel="stylesheet" href="{{ pathto('_static/' + style, 1) }}" type="text/css" />
jinja2.exceptions.UndefinedError: 'style' is undefined

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/tedana/envs/959/lib/python3.8/site-packages/sphinx/cmd/build.py", line 290, in build_main
    app.build(args.force_all, args.filenames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/tedana/envs/959/lib/python3.8/site-packages/sphinx/application.py", line 351, in build
    self.builder.build_update()
  File "/home/docs/checkouts/readthedocs.org/user_builds/tedana/envs/959/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 290, in build_update
    self.build(to_build,
  File "/home/docs/checkouts/readthedocs.org/user_builds/tedana/envs/959/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 360, in build
    self.write(docnames, list(updated_docnames), method)
  File "/home/docs/checkouts/readthedocs.org/user_builds/tedana/envs/959/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 567, in write
    self._write_serial(sorted(docnames))
  File "/home/docs/checkouts/readthedocs.org/user_builds/tedana/envs/959/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 577, in _write_serial
    self.write_doc(docname, doctree)
  File "/home/docs/checkouts/readthedocs.org/user_builds/tedana/envs/959/lib/python3.8/site-packages/sphinx/builders/html/__init__.py", line 675, in write_doc
    self.handle_page(docname, ctx, event_arg=doctree)
  File "/home/docs/checkouts/readthedocs.org/user_builds/tedana/envs/959/lib/python3.8/site-packages/sphinx/builders/html/__init__.py", line 1105, in handle_page
    raise ThemeError(__("An error happened in rendering the page %s.\nReason: %r") %
sphinx.errors.ThemeError: An error happened in rendering the page api.
Reason: UndefinedError("'style' is undefined")

Theme error:
An error happened in rendering the page api.
Reason: UndefinedError("'style' is undefined")
```

### Next Steps

Hopefully someone with some free time and experience with jinja2 and/or Sphinx can take a look.

### LINKED ISSUE #967: Style test is not passing
### Summary

The style tests are not passing, showing the error below.

I don't know if something changed with `black` or we somehow missed these.

### Additional Detail

```
tedana/selection/selection_utils.py:46:9: E721 do not compare types, for exact checks use `is` / `is not`, for instance checks use `isinstance()`
tedana/selection/selection_utils.py:48:9: E721 do not compare types, for exact checks use `is` / `is not`, for instance checks use `isinstance()`
tedana/selection/selection_utils.py:53:11: E721 do not compare types, for exact checks use `is` / `is not`, for instance checks use `isinstance()`
tedana/selection/selection_utils.py:60:11: E721 do not compare types, for exact checks use `is` / `is not`, for instance checks use `isinstance()`
tedana/workflows/ica_reclassify.py:215:10: E721 do not compare types, for exact checks use `is` / `is not`, for instance checks use `isinstance()`
tedana/workflows/ica_reclassify.py:218:10: E721 do not compare types, for exact checks use `is` / `is not`, for instance checks use `isinstance()`
make: *** [Makefile:16: lint] Error 1

Exited with code exit status 2
```

### PR DESCRIPTION
**Pull request by eurunuela**
Closes #967, Closes #961

Changes proposed in this pull request:

- Uses `type(a) is list` instead of `type(a) == list`.
- Increases the minimum version required for sphinx to 6.2.1 and sphinx_rtd_theme to 1.2.2, which should not use the removed mention of style.

### CODE REVIEW

**Comment by handwerkerd** [comment]
Both this PR and #966 look good to me, but they are separately failing checks (RTD build for this one and style for the RTD fix). Can you combine these changes into a single PR so that all the checks pass before merging? Otherwise I'm fine approving both and merging separately.

**Review by handwerkerd — DISMISSED** [review]
LGTM. As I mentioned in a comment, I think it would be better to have one PR with this and #966 so that all checks pass, but I'll approve this in case we decide to merge separately.

**Comment by eurunuela** [comment]
I can merge this with the other PR tomorrow. But I don't mind if they get merged separately either.

**Comment by eurunuela** [comment]
This PR is quite simple and is mostly testing-related. I think 1 approval would be enough.

Thoughts @handwerkerd?

**Review by handwerkerd — APPROVED** [review]
LGTM.
This is fairly minor and holding up a bunch of other PRs. I'll give @tsalo @n-reddy @marco7877  and @dowdlelt a few hours to see if they object and want to check this more carefully. Otherwise, I'll merge with just my approving review.

**Review by dowdlelt — APPROVED** [review]
Super simple, knock it out!

**Pull request merged**
