### PR TITLE
[DOC] Reorganize documentation

### LINKED ISSUE #677: Reorganize RTD tree
### Summary
I think our current sidebar/organization is a little suboptimal, so I'd like to restructure it a bit. I've opened this issue so we could discuss my idea.

### Additional Detail

Here's my proposal (happy to amend):

```
- Installation  # add instructions to install from GitHub source
- About multi-echo fMRI  # new page
    - What is multi-echo fMRI?
        - Current sections on physics, why to use, considerations, and costs and benefits.
    - Acquiring multi-echo fMRI
        - Current sections on available sequences, parameter recommendations, and common parameters
    - Processing multi-echo fMRI  # moved from "Using tedana" page
    - General resources  # renamed from "Resources"
- Using tedana from the command line  # renamed from "Using tedana"
    - Running the tedana workflow  # renamed from "Running tedana"
    - Running the t2smap workflow  # renamed from "Running t2smap"
- tedana's denoising approach  # renamed from "The tedana pipeline"
- Outputs of tedana
    - tedana derivatives
    - Component tables
    - Citable workflow summaries
    - ICA Components Report  # moved from its own page
- FAQ  # drop "tedana" and "multi-echo fMRI" subsections and add prefixes (e.g., "[tedana]") to questions
- Support and communication
- What's New  # see #676 
- Contributing to tedana
    - Developer guidelines  # moved from its own page
    - Governance  # moved from its own page
- The tedana roadmap
    - Scope of tedana  # moved from contributing page
- API
```

### PR DESCRIPTION
**Pull request by tsalo**
Closes #677.

Changes proposed in this pull request:

- Reorganize the documentation tree.
- Fix the module role in the tedpca docstring.

### CODE REVIEW

**Comment by tsalo** [comment]
Cancelling the integration tests because this only impacts the documentation. I'll use my admin privileges to merge once I have the necessary reviews.

**Review by jbteves — APPROVED** [review]
LGTM, this is awesome, thanks @tsalo !

**Review by emdupre — APPROVED** [review]
This looks great, thank you @tsalo !

My only real feedback is that it looks like "Processing multi-echo fMRI" was moved to "About ME-fMRI" from its previous grouping under "Using tedana." At least with the current wording, I feel like the connection to the surrounding content is a bit more tenuous now than it was previously.

I don't think that should hold up this PR (!), but maybe we can open an issue about updating the wording in "Processing multi-echo fMRI" to harmonize and highlight a more general, non-tedana framing.

**Comment by tsalo** [comment]
Thanks @emdupre! I've opened #755 for that and I'll merge this PR now.

**Pull request merged**
