### PR TITLE
[RF] Reorganize package further.

### PR DESCRIPTION
**Pull request by tsalo**
Based on discussion in #30, I have reorganized the package to have the following structure:

- `tedana.model`
    - `tedana.model.monoexponential`: contains `fit_decay` and `fit_decay_ts`
    - `tedana.model.fit`: contains `fitmodels_direct` and associated functions, minus the `getelbow` functions
    - `tedana.model.combine`: contains `make_optcom`
- `tedana.decomposition`
    - `tedana.decomposition.eigendecomp`: contains `tedpca` and `tedica`
    - `tedana.decomposition._utils`: contains `eimask`
- `tedana.selection`
    - `tedana.selection.select_comps`: contains `selcomps`, to be broken into separate functions
        - Also might need a better name, to distinguish it from other potential selection methods (if anyone has any they want to contribute)
    - `tedana.selection._utils`: contains the `getelbow` functions, because I think they belong here, rather than in `tedana.model`

### CODE REVIEW

**Comment by emdupre** [comment]
This is great !! 🎉 Sorry for the delay in looking it over. 

The one question I have: do you think we should also merge the `io` and `utils` modules in this refactor ?

**Comment by tsalo** [comment]
We definitely can, but I held off on it because I'm not sure how to organize it. Should it be `tedana.utils.utils` and `tedana.utils.io` or should all of the functions from `tedana.io.input_data` and `tedana.io.output_data` go into the `tedana.utils` script?

**Comment by emdupre** [comment]
I would think the first option, unless anyone else has another preference ! Tagging @rmarkello since he suggested this organization in #30

**Comment by tsalo** [comment]
@rmarkello Sorry, do you mean `tedana.io` and `tedana.utils` or `tedana.utils.io` and `tedana.utils.utils` (with all of the functions initialized at the `tedana.utils` level so users can access them there?

**Comment by rmarkello** [comment]
Apologies for being unclear! I think `tedana.utils.io` and `tedana.utils.utils` would be the best, with the functions initialized in `tedana.utils` as you suggest, and we can see how it goes!

**Comment by tsalo** [comment]
@rmarkello Okay, that makes sense. Thanks! The new commit should handle that.

**Comment by emdupre** [comment]
This looks good to me, thanks !! Merging !

**Pull request merged**
