### PR TITLE
[TST] Additional smoke tests for stats.py 

### PR DESCRIPTION
**Pull request by monicayao**
Addresses #376  .

Changes proposed in this pull request:

- Additional smoke tests for the stats functions in three different files 
- A bug was discovered, in which get_coeff cannot take in a 3D data when the docstring for the function had claimed that it could

### CODE REVIEW

**Comment by tsalo** [comment]
@emdupre @jbteves Does anyone have any idea how the coverage is _decreasing_ here?

**Comment by jbteves** [comment]
@monicayao great catch on that bug!
@tsalo I'm pretty baffled too. If I'm reading the report correctly, it thinks that `test_decay` is no longer covering anything, and coverage is decreasing by 5 lines. But I don't see anything in the diffs for this PR that would cause that.

**Comment by jbteves** [comment]
Okay I looked through all of the commits individually and the only thing I noticed is that at some point we added coverage for Python 3.6, but that coverage addition should be in both `master` and the PR if I understand how the bot works correctly. The only other thing I can think of is that the bot ran last time without the 3.6 coverage somehow and this time it added the 3.6 coverage for the PR but not for the last time it ran with master, but that still doesn't make a whole lot of sense...

**Comment by emdupre** [comment]
Closing as a duplicate of #386. If that's not correct, @monicayao , please re-open !

**Pull request closed without merging**
