### PR TITLE
[FIX] Adds check for just one component

### LINKED ISSUE #402: tedana ICA fails to converge
Hi

I'm running tedana on a 3 echo data set that has been distortion corrected with either fugue or topup -- the undistorted images look correct.  The ICA step fails to converge, and then tedana fails at the spatial clustering of components -- how can I proceed with / fix this situation?  Thanks.

Module `duecredit` not successfully imported due to "No module named 'duecredit'". Package functionality unaffected.
/mnt/home/keschenb/anaconda3/lib/python3.6/site-packages/sklearn/externals/joblib/__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.
23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serializ
e those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)
INFO:tedana.workflows.tedana:Using output directory: ./ME3/fugue
INFO:tedana.workflows.tedana:Loading input data: ['rest_e1_pos_undistorted.nii.gz', 'rest_e2_pos_undistorted.nii.g
z', 'rest_e3_pos_undistorted.nii.gz']
INFO:tedana.workflows.tedana:Using user-defined mask
INFO:tedana.workflows.tedana:Computing T2* map
INFO:tedana.combine:Optimally combining data with voxel-wise T2 estimates
INFO:tedana.decomposition.eigendecomp:Computing PCA of optimally combined multi-echo data
INFO:tedana.decomposition.eigendecomp:Loading PCA from: pcastate.pkl
INFO:tedana.decomposition.eigendecomp:Selected 149 components with MLE dimensionality detection
WARNING:tedana.decomposition.eigendecomp:ICA attempt 1 failed to converge after 500 iterations
WARNING:tedana.decomposition.eigendecomp:Random seed updated to 43
WARNING:tedana.decomposition.eigendecomp:ICA attempt 2 failed to converge after 500 iterations
WARNING:tedana.decomposition.eigendecomp:Random seed updated to 44
WARNING:tedana.decomposition.eigendecomp:ICA attempt 3 failed to converge after 500 iterations
WARNING:tedana.decomposition.eigendecomp:Random seed updated to 45
WARNING:tedana.decomposition.eigendecomp:ICA attempt 4 failed to converge after 500 iterations
WARNING:tedana.decomposition.eigendecomp:Random seed updated to 46
WARNING:tedana.decomposition.eigendecomp:ICA attempt 5 failed to converge after 500 iterations
WARNING:tedana.decomposition.eigendecomp:Random seed updated to 47
WARNING:tedana.decomposition.eigendecomp:ICA attempt 6 failed to converge after 500 iterations
WARNING:tedana.decomposition.eigendecomp:Random seed updated to 48
WARNING:tedana.decomposition.eigendecomp:ICA attempt 7 failed to converge after 500 iterations
WARNING:tedana.decomposition.eigendecomp:Random seed updated to 49
WARNING:tedana.decomposition.eigendecomp:ICA attempt 8 failed to converge after 500 iterations
WARNING:tedana.decomposition.eigendecomp:Random seed updated to 50
WARNING:tedana.decomposition.eigendecomp:ICA attempt 9 failed to converge after 500 iterations
WARNING:tedana.decomposition.eigendecomp:Random seed updated to 51
WARNING:tedana.decomposition.eigendecomp:ICA attempt 10 failed to converge after 500 iterations
INFO:tedana.workflows.tedana:Making second component selection guess from ICA results
INFO:tedana.combine:Optimally combining data with voxel-wise T2 estimates
INFO:tedana.model.fit:Fitting TE- and S0-dependent models to components
INFO:tedana.model.fit:Performing spatial clustering of components
Traceback (most recent call last):
  File "/mnt/home/keschenb/anaconda3/bin/tedana", line 10, in <module>
    sys.exit(_main())
  File "/mnt/home/keschenb/anaconda3/lib/python3.6/site-packages/tedana/workflows/tedana.py", line 453, in _main
    tedana_workflow(**vars(options))
  File "/mnt/home/keschenb/anaconda3/lib/python3.6/site-packages/tedana/workflows/tedana.py", line 379, in tedana_workflow
    n_echos)
  File "/mnt/home/keschenb/anaconda3/lib/python3.6/site-packages/tedana/selection/select_comps.py", line 276, in selcomps
    np.min(comptable.loc[acc_prov, 'variance explained'])))
ZeroDivisionError: float division by zero

### PR DESCRIPTION
**Pull request by jbteves**
Closes #402 

Changes proposed in this pull request:

- Adds a check to see if there is only one component, failing if so
- Averts a downstream error if there is only one component by failing earlier

TODO:
- Double-check that this actually stops the error, I need some data with only one component to be sure. 
- Do we need to also ignore that component to stop the downstream from thinking we only have one?

### CODE REVIEW

**Comment by jbteves** [comment]
@emdupre @tsalo pinged you to make sure this is an okay first pass.

**Comment by tsalo** [comment]
I recommend making the if statement above check for `<= 1` instead of having two separate ones.

**Comment by jbteves** [comment]
I left it because I wasn't sure if I need to change the classification of the only surviving component to stop it from the downstream error. If not then yeah, I'll just change it to `<= 1`.

**Comment by emdupre** [comment]
> I left it because I wasn't sure if I need to change the classification of the only surviving component to stop it from the downstream error. 

Let's go ahead and change to `<= 1`, please !

**Comment by emdupre** [comment]
Doesn't this close #402 ?

**Comment by jbteves** [comment]
@emdupre I need an approval to merge this.

**Comment by tsalo** [comment]
And drop WIP from the name.

**Pull request merged**
