### PR TITLE
[DOC] Add warning about not using release-drafter releases to developer instructions

### PR DESCRIPTION
**Pull request by tsalo**
Closes None.

Changes proposed in this pull request:

- Add a warning box about not directly releasing release-drafter release drafts (😆).

A screenshot:

image

### CODE REVIEW

**Review by jbteves — APPROVED** [review]
Impressive amount of extra whitespace getting trimmed 😆

**Comment by tsalo** [comment]
> Impressive amount of extra whitespace getting trimmed 😆

LOL yeah I didn't even realize we had a trailing whitespace problem.

Once we merge this we'll be good to release, right?

**Comment by jbteves** [comment]
Correct! If you feel it's pressing I'll go ahead and release, but I figured this would be a better point to release from since it has the instructions updated.

**Review by emdupre — APPROVED** [review]
This LGTM ! New release here we come !! :rocket:

**Pull request merged**
