### PR TITLE
[ENH] Adds binder requirements file

### PR DESCRIPTION
**Pull request by souravsingh**
Fixes a part of #149 

The binder link(which is currently showing an error) is here- https://mybinder.org/v2/gh/souravsingh/tedana/tree/add-binder

### CODE REVIEW

**Comment by KirstieJane** [comment]
Hi @souravsingh - is there anything we can do to help you get the data? Happy to answer any questions if you have them! 😸

**Comment by souravsingh** [comment]
@KirstieJane I am working on creating the example notebooks. One of the WIP sample can be accessed here- https://colab.research.google.com/drive/1waBaNSzBsKgpiJZc0v770WWPRK9ZEFqR

Let me know if any improvements are needed on the notebook

**Comment by KirstieJane** [comment]
No problem! And no rush. I just wanted to check to make sure you weren’t stuck on getting the data :smiley_cat:

Thanks for sharing the draft! Let me know if you have any questions ✨

**Comment by souravsingh** [comment]
@KirstieJane Thanks for the reply!
I am not able to find the mask being used for the analyses. Is the mask something that should be downloaded separately or is it something which is generated through `compute_background_mask` method for nilearn? 

I ask this since I didn't find any mask file in the OSF directory

**Comment by tsalo** [comment]
I believe that the mask file is an output of tedana that we've since removed, since we can reconstruct it from the adaptive mask file. You can replace `mask.nii` with `adaptive_mask.nii` (which you should be getting when you run tedana with verbose outputs), but you'll need to binarize it before using it with `apply_mask` in the notebooks. One method that will work is

```python

mask_file = 'adaptive_mask.nii'  # but with the path and everything
mask_img = nib.load(mask_file)
mask_data = mask_img.get_data()
mask_data = (mask_data != 0).astype(int)
mask_img = nib.Nifti1Image(mask_data, mask_img.affine)
```

although it's probably possible to use nilearn's [math_img](https://nilearn.github.io/modules/generated/nilearn.image.math_img.html#nilearn-image-math-img) to do it more simply.

**Comment by souravsingh** [comment]
@KirstieJane This is totally unrelated to the PR, but I have created a document for the project proposal, which can be accessed here- https://docs.google.com/document/d/12FPCjzhZgOGFklKjdMjIpr8-zUpKbR0-nh1J4v8uSso/edit?usp=sharing

I would like to get your feedback on the proposal.

**Comment by souravsingh** [comment]
@tsalo Can you review the proposal I have written?

**Comment by souravsingh** [comment]
@tsalo @KirstieJane I have created a notebook here- https://colab.research.google.com/drive/1waBaNSzBsKgpiJZc0v770WWPRK9ZEFqR

I am not able to display any of the plots, even after using `show()`.

**Comment by souravsingh** [comment]
@KirstieJane I have added a preliminary example for tedana. Can you review?

**Comment by souravsingh** [comment]
@tsalo I have added an example for tedana. Can you take a look?

**Comment by tsalo** [comment]
The notebook looks great! Just a couple of notes:
1. Since you're running `tedana` within the workflow, we might as well consolidate the notebooks (instead of separating the optimal combination figures from the denoising figures). Why don't you rename the notebook to `tedana_workflow_plots.ipynb`.
2. You should use `tedana.workflows.tedana_workflow` and run the workflow in Python rather than running it through the command line within the notebook.
3. Could you add more markdown section headings? Without evaluating the notebook, it's difficult to figure out what each plot should contain. Even once the plots are generated, it will be very helpful to people.
4. I'm not sure how Binder best deals with data (e.g., where it should be saved and whether it needs to be cleaned up in the end), but that may impact how the data should be handled in the notebook.

**Pull request closed without merging**
