### PR TITLE
[FIX] Fix/revert changes

### PR DESCRIPTION
**Pull request by jbteves**
Closes None

Changes proposed in this pull request:

- Reverts several commits to see if the problem is in the commits or a CI bug.
-

### CODE REVIEW

**Comment by jbteves** [comment]
Bizarrely all of the combos of commits are producing a *different* error than the one on master.

**Comment by tsalo** [comment]
That's just the product of using coverage v5.0.2 (the latest release). It's because it's the first time our environment has been built from scratch in a while. I fixed it in #518 with 631557b68cbda4755069a17a688306e8ede0dbb3.

**Comment by jbteves** [comment]
I see; where does it state that so I know for future reference? Then I'll close this. Thanks for working on #518

**Comment by tsalo** [comment]
A frustrating amount of Googling led me to github.com/nedbat\\/coveragepy\/issues/716. I have no clue how to post a URL without linking to the issue (which then posts a cross-link on that issue, which I don't want), so apologies for the errant backslash.

**Comment by emdupre** [comment]
Can we close this in favor of #518 , @jbteves ?

**Comment by jbteves** [comment]
Ack, I mistakenly thought this was closed already.

**Pull request closed without merging**
