### PR TITLE
[TST] Allow CI for all-contributors

### LINKED ISSUE #628: Allow CI for all-contributors
### Summary
Right now we skip CI for all-contributors because presumably changing the contributor table shouldn't change the code results. However, it doesn't properly allow us to merge the pull requests as usual because we don't have the passing checks. I propose we simply allow CI, which is simpler than conditionally requiring checks or not, even though it's wasteful of cloud time.

### PR DESCRIPTION
**Pull request by jbteves**
Closes #628 

Changes proposed in this pull request:

- Deploys CI for all-contributors so we can review it like normal pull requests

### CODE REVIEW

**Comment by tsalo** [comment]
This seems like a reasonable change. I will approve once tests pass. Can we close and re-request #626 once this is merged as a test?

**Comment by jbteves** [comment]
I'm fine with that. The other thought is that we may want to add credit for bringing to our attention this potential difference in results from different python versions.

**Comment by tsalo** [comment]
Okay, good point. So maybe instead we merge #626 and then make a new request for the bug report once we have an issue for the Python version weirdness.

**Review by eurunuela — APPROVED** [review]

**Comment by handwerkerd** [comment]
It would be nicer to have a way to avoid testing the code every time we make a documentation change, but, currently, this seems like a reasonable solution.

**Review by handwerkerd — APPROVED** [review]

**Pull request merged**
