### PR TITLE
[DOC] Added MAPCA to list of dependencies

### PR DESCRIPTION
**Pull request by handwerkerd**
I noticed that mapca isn't listed in the current dependencies, so I added it.

Changes proposed in this pull request:

- Added mapca to the list of dependencies in README.md
- Not sure if there's anywhere else mapca should be listed as a dependency.

### CODE REVIEW

**Review by jbteves — APPROVED** [review]
Ultimately `pip` should correctly fetch the packages, but good catch! Thanks @handwerkerd !

**Review by tsalo — APPROVED** [review]

**Review by tsalo — CHANGES_REQUESTED** [review]
Just realized it should be updated in https://github.com/ME-ICA/tedana/blob/main/docs/installation.rst as well.

**Review by tsalo — APPROVED** [review]
Thanks!

**Comment by handwerkerd** [comment]
FWIW, the reason I noticed this is I used `python setup.py develop` instead of pip. Maybe I should be using pip, but this did help me notice this omission. :)

**Comment by tsalo** [comment]
We should probably recommend using [`python -m pip install -e .`](https://packaging.python.org/tutorials/installing-packages/#installing-from-a-local-src-tree) instead. That _should_ install the dependencies automatically. Not sure why `python setup.py develop` doesn't, but it might be a bug in our packaging?

**Comment by handwerkerd** [comment]
We do recommend `pip -e` in https://github.com/ME-ICA/tedana/blob/main/CONTRIBUTING.md#3-run-the-developer-setup but I did this a while ago & got used to the other method. Thinking about this a bit more, I suspect the issue is that I had already installed tedana as a developer, which updates the code being executed, but probably doesn't automatically download new dependencies when the code is updated.

**Review by jbteves — APPROVED** [review]

**Pull request merged**
