### PR TITLE
[DOC] Generalize preprocessing recommendations

### LINKED ISSUE #755: Generalize "Processing multi-echo fMRI" section of docs
### Summary

With #740, the documentation were reorganized and the "Processing multi-echo fMRI" section was moved from "Using tedana" to "About ME-fMRI". Unfortunately, at the moment, that section is pretty tedana-specific, and includes very little general information about processing ME-fMRI data. We'd like to add some stuff about processing this kind of data in general, as well as change `tedana` to `multi-echo denoising` in the processing descriptions.

This stems from https://github.com/ME-ICA/tedana/pull/740#pullrequestreview-707672224.

### PR DESCRIPTION
**Pull request by tsalo**
Closes #755.

Changes proposed in this pull request:

- Replace `tedana` with "multi-echo denoising" in recommendations for preprocessing multi-echo data.
- Add a step about motion correction.

### CODE REVIEW

**Review by handwerkerd — APPROVED** [review]
LGTM.
My one critique is that, when I do normalize, I've tended to do one normalization before tedana because it's better to do only one spatial transform. That step shouldn't mess up the relationship between echoes more than motion correction (though normalization with aggressive non-linear warping might). I don't think we clearly know what is better or worse yet so the next could be more nuanced in this area. This is a critique of the current recommendations, not the changes in this PR, so there's no reason to hold this PR up to discuss this issue.

**Comment by tsalo** [comment]
Maybe we could include the caveat that that part, at least, is based on theory rather than empirical evidence?

**Review by handwerkerd — APPROVED** [review]

**Review by jbteves — APPROVED** [review]
LGTM, thanks @tsalo ! I think this will be a bit easier to point people to since I've heard questions about motion correction with multi-echo several times now.

**Comment by tsalo** [comment]
Thanks @jbteves and @handwerkerd! Merging now.

**Pull request merged**
