### PR TITLE
Fix Bibtex rendering in reports

### LINKED ISSUE #986: Fix reference rendering in HTML report
### Summary

In `tedana_report.html` files LaTeX formatting for references are not rendering correctly.

### Additional Detail

For example, see https://me-ica.github.io/ohbm-2023-multiecho/tedana/tedana_results_kundu_five-echo/tedana_report.html
The raw LaTeX typesetting appears in the HTML

### PR DESCRIPTION
**Pull request by eurunuela**
Closes #986

Changes proposed in this pull request:

- The PR adds a new function `_bib2html()` that converts the contents of the bibtex file to an HTML string.
- The PR adds two dependencies to deal with the bibtex to HTML conversion.

### CODE REVIEW

**Comment by eurunuela** [comment]
Can we please add @martaarbizu and @martinezeguiluz as contributors?

**Review by handwerkerd — COMMENTED** [review]
Thank you for working on this @eurunuela I noticed that the references are properly rendering at the bottom of the report, but the citations in the "About Tedana" section are still not rendering (see screenshot). Looking at your edits, I'm not sure you directly address the in-text citations. Should that be left for a separate PR or addressed here?

Also, this is minor, but, with the current rendering, it might look nicer with a line of whitespace between each full reference.
image

**Comment by eurunuela** [comment]
The main issue is the citekey for Hunter 2007. I updated the bib file but the tests are still failing but I don't know why. @tsalo @handwerkerd any idea why?

**Comment by notZaki** [comment]
@eurunuela Does the key for Hunter need to be updated at https://github.com/eurunuela/tedana/blob/0668d67912c511e65a9d84554ad00ce6b44b0f45/tedana/workflows/tedana.py#L858

**Comment by eurunuela** [comment]
Ah good catch @notZaki! I forgot we hardcoded the references. Just updated those files.

**Comment by notZaki** [comment]
@eurunuela I was playing around with it a bit. Sent a PR to your branch. Might fix some stuff, might break other things. 🎲

**Comment by eurunuela** [comment]
Thank you @notZaki! I didn't really tried to optimize the code. It was a quick PR, so thank you for tackling that. I don't have access to my laptop until Sunday. I'll merge then.

**Comment by eurunuela** [comment]
It looks great now, thank you @notZaki!

This is ready for review.

**Review by handwerkerd — APPROVED** [review]
LGTM!
Thank you to @eurunuela and @notZaki  for isolating and fixing this issue!

**Review by dowdlelt — APPROVED** [review]
Go for it - looks good to me, text seemed to render correctly! nice work per usual

**Pull request merged**
