### PR TITLE
[STY] Format package with Black

### LINKED ISSUE #219: Automate code formatting
### Summary
This is just something that came up recently in the [python_pals](https://brainhack.slack.com/messages/C2Y1T5XDJ) BrainHack Slack channel, although I think we've discussed it before informally. If we use [Black](https://black.readthedocs.io/en/stable/), we can reduce the amount of mental overhead we need for dealing with coding style. Not having to worry about style will also make it easier for new contributors.

### Next Steps
1. Add instructions for using Black to contributing guidelines. All contributors should have to do is run it on the package prior to opening a PR.
2. Run Black on the package and merge in a new PR to get things started.

### PR DESCRIPTION
**Pull request by tsalo**
Closes #219. This is also a test of the new PR drafting feature from GitHub, to see if we need the [WIP] PR prefix anymore, which is why I'm opening before we've actually discussed using Black in the issue.

Changes proposed in this pull request:
- Format the whole package with [Black](https://black.readthedocs.io/en/stable/).

### CODE REVIEW

**Comment by tsalo** [comment]
Black and flake8 don't seem to get along. ☹️

**Comment by emdupre** [comment]
If it's going to cause more problems with Flake8, I think that's probably a good data point against adoption.... WDYT ?

**Comment by tsalo** [comment]
I agree, although I'm surprised that two PEP8 style tools would fight like this. Still, I think we need something that we can use to tune up the package at regular intervals. What about [YAPF](https://github.com/google/yapf)?

**Comment by emdupre** [comment]
Sorry, what is the rationale for tuning up the package ? We have linting in place with Travis, so I'm not sure where style errors should be introduced.

Thanks for talking through this !

**Comment by emdupre** [comment]
.@tsalo should I close this and we can continue the discussion on automatic code formatters in #219 ?

**Comment by tsalo** [comment]
Sounds good to me.

**Pull request closed without merging**
