### PR TITLE
[REF] Replace deprecated get_data with get_fdata

### PR DESCRIPTION
**Pull request by notZaki**
Closes none.

I don't think this will change any of the results, but should clear up most of the warnings in the tests.

### CODE REVIEW

**Review by tsalo — APPROVED** [review]
LGTM. Are you confident you caught all instances of `get_data()`?

**Comment by notZaki** [comment]
I think so. `grep -ri get_data .` returned zilch.

**Comment by tsalo** [comment]
Awesome, thanks!

**Review by eurunuela — APPROVED** [review]
Love it. Thanks @notZaki !

**Review by jbteves — APPROVED** [review]
Thanks for doing this, I was actually going to hit this today but you beat me to it yesterday!
LGTM

**Pull request merged**
