### PR TITLE
[DOC] Add Paused label description to CONTRIBUTING

### LINKED ISSUE #257: Add Pause tag to Issues
### Summary
Add a pause tag to some issues so that people don't work on them if there is a conflicting priority

### Additional Detail
The pause tag would be used in instances of refactoring or the necessity of diverting attention to a pressing issue. For example, if we're refactoring a section of code, it doesn't make sense for people to work on documentation in that section since it will likely change. The expectation would be that paused issues should NOT be worked on. For now, we will have to manually add/subtract the pause tag until workflows are more settled. 

### Next Steps
I would like to add the pause tag pending approval from @emdupre, @tsalo, @KirstieJane. If anybody is opposed to adding this tag, they should comment below outlining why they think it's a bad idea. 
- [x] Add the tag (Thanks @tsalo !)
- [ ] Add notes to CONTRIBUTING to indicate usage of the tag (PR #278 would complete this task)

### PR DESCRIPTION
**Pull request by jbteves**
Closes #257 by adding to CONTRIBUTING guidelines

Changes proposed in this pull request:

- Adds description of paused tag to CONTRIBUTING

### CODE REVIEW

**Comment by jbteves** [comment]
I'm a little confused about that too, but I think the problem is that in the commit history for the repo the commits are a different hash, so it thinks that mine are a different commit that reflects the same change rather than being the same commit (like [here](https://github.com/ME-ICA/tedana/commit/47f352b051c23e900878dcd570dcdc619dd445f0) the commit has the PR title, but on the commit in my history it's a different title). Maybe I merged the upstream master improperly? I can try to fix that before we merge it, though if it's squashed then this mistake won't get folded into the repo.

**Comment by emdupre** [comment]
With squash and merge I wouldn't worry about it :) Merge when ready !

**Comment by jbteves** [comment]
Before I squash, do you have any guidelines for how you'd like the resulting commit to read? My plan was to just note that CONTRIBUTING is updated to reflect the new pause label, cutting out all of the junk my bad history includes.

**Comment by emdupre** [comment]
That sounds reasonable to me :)

We don't have any guidelines here, but I think your plan sounds great !

**Comment by jbteves** [comment]
Don't merge this-- another rebase error.

**Comment by emdupre** [comment]
Let us know when this is ready for another review, @jbteves !

**Comment by jbteves** [comment]
@emdupre it's actually ready; sorry, I think it got lost in some Gitter chatter and I should have put that here.

**Comment by jbteves** [comment]
Lol it’s fine, merging.

**Pull request merged**
