### PR TITLE
[FIX] Propagate TR to ref_image header

### LINKED ISSUE #206: TR isn't set correctly in output
When running the current version of tedana, it appears that the TR of the output data is set to 1.00. 

It looks like this occurs around line 638 in io.py, where the ref image is created. Specifically the variable img had a complete header, with the appropriate TR available via the get_zooms function (http://nipy.org/nibabel/nibabel_images.html):
```
good_header = img.header
good_header.get_zooms()[-1]
```
However, the TR information has been removed/replaced(?) with the ref image, such that get_zooms only has the voxel dimensions.

### PR DESCRIPTION
**Pull request by dowdlelt**
Closes #206  .

Changes proposed in this pull request:

- in load_data, the ref image now has a 4th dimension, TR in output is now correct
-

### CODE REVIEW

**Comment by dowdlelt** [comment]
Travis is unhappy with that extra '1', unsurprisingly. Though I will admit this is the first time I have ever encountered continuous integration. 

```
 assert ref.shape == (39, 50, 11)
E       assert (39, 50, 11, 1) == (39, 50, 11)
E         Left contains more items, first extra item: 1
E         Use -v to get the full diff
```

**Comment by tsalo** [comment]
This looks good. Thank you!

It looks like you'll just need to update the test. You just need to change `assert ref.shape == (39, 50, 11)` to `assert ref.shape == (39, 50, 11, 1)` in the test function.

Could you also check to see if the 3D images being written out are still 3D? I just want to make sure that they aren't written out with a singleton fourth dimension.

Lastly, could you add the [FIX] prefix to this PR title and remove the [bug] one from the corresponding issue?

**Comment by dowdlelt** [comment]
3dinfo reports that dn_ts_OC.nii has a time dimension, with the correct tr, whereas s0v.nii has no time dimension. Opens fine in AFNI as well. Let me know if you want another check of that.

**Comment by tsalo** [comment]
If it has no time dimension then I think that should be fine. Thank you for checking!

**Comment by emdupre** [comment]
I'll go ahead and merge, then ! Thanks @dowdlelt :sparkles:

**Pull request merged**
