### PR TITLE
Remove accepted and rejected time series from the standard file outputs and change denoised time series name

### LINKED ISSUE #819: Remove accepted and rejected time series from the standard file outputs
### Summary

The terminology for the 'denoised' vs 'accepted' time series is confusing to end users and saving both of these files is a waste of space most of the time. The proposal is to stop saving these time series and making the documentation a bit more explicit on how an end user can generate these files as needed.

This is based on a comment by @emdupre in the [Oct 2021 dev call.](https://docs.google.com/document/d/1IYthF4JxKhWxrxpV8C61SGdjNbIYnRI8L294eP9D6cg/edit?usp=sharing)

### Next Steps

- Decide if others agree to move forward on this
- Decide if there's anything we can do to make it easier for an end user to generate and save these files or, if it's already easy enough, clearly document how to do it.

### PR DESCRIPTION
**Pull request by martaarbizu**
Closes #819  .

Changes proposed in this pull request:

- Remove accepted and rejected time series from the standard file outputs
- Change the name of optcomDenoised to denoised

### CODE REVIEW

**Review by eurunuela — APPROVED** [review]
LGTM! @tsalo @handwerkerd what do you think?

**Comment by handwerkerd** [comment]
Thank you for taking care of this.
I just opened a PR to @martaarbizu's branch to update the API documentation to reflect these changes.

I'd want @tsalo's option, but I'd lean against changing `optcomDenoised` to `denoised`. Other programs that use these file names, like fMRIPrep & personal scripts, would likely need to make a change to properly process files. I like `denoised` slightly more, but both names are fine and I'll lean against a change that will break other people's scripts unless we have a strong reason to do so.

That said, I am labeling this as a "breaking change" since we are altering default outputs (even if they are default outputs no one actually uses)

**Comment by tsalo** [comment]
>I'd want @tsalo's option, but I'd lean against changing optcomDenoised to denoised. Other programs that use these file names, like fMRIPrep & personal scripts, would likely need to make a change to properly process files. I like denoised slightly more, but both names are fine and I'll lean against a change that will break other people's scripts unless we have a strong reason to do so.

I believe that I had this filename change in my version as well. FWIW, fMRIPrep only uses the t2smap workflow, so it doesn't produce/use the denoised file. No matter what, this will be a breaking change (there's always the possibility that some users are using the files that this PR removes), so I say we go for broke and rename everything we think would benefit from a change.

**Comment by handwerkerd** [comment]
@tsalo Does BIDS care if `denoised` is or is not capitalized? If not, once my additions to the comments are added, I'm fine with this merging. When we release the next version, we should make a non-trivial note that we've changed a file name because that will affect people.

**Comment by tsalo** [comment]
There's no rule about the naming, as long as we stick to alphanumeric strings. I personally prefer lower-case or lowerCamelCase, but that's not required at all.

**Comment by handwerkerd** [comment]
@martaarbizu Thank you again for working on this. I made a pull request onto your PR to improve the documentation. You should be able to approve and merge https://github.com/martaarbizu/tedana/pull/1 into your PR and then this will be ready to merge into Main.

**Pull request closed without merging**
