### PR TITLE
[ENH] Rename modules

### PR DESCRIPTION
**Pull request by frodeaa**
Closes # https://github.com/ME-ICA/tedana/issues/135.

Changes proposed in this pull request:
 - renaming `model.monoexponential` to `decay`
 - renaming `model.combine to combine`
 - reorganizing `io` and `utils`
   - move `new_nii_like()`, `filewrite()`, `load_data()` from `utils` to `io`

remains to fix the documentation `docs/api.rst`

### CODE REVIEW

**Comment by emdupre** [comment]
Welcome to `tedana`, @frodeaa, and thanks so much for a fantastic first pull request ! :tada:

It looks like this is still WIP -- just let me know when you're ready for a review ! It looks great so far, though, and we really appreciate the contribution :smile:

**Comment by tsalo** [comment]
@frodeaa This looks great. Would you mind moving `gscontrol_mmix` from `io` to `utils`? It really belongs somewhere else, but for the moment `utils` seems more appropriate than `io`.

**Comment by frodeaa** [comment]
@tsalo `gscontrol_mmix` moved to `utils`

ready for review

**Comment by rmarkello** [comment]
Thanks so much for all this work, @frodeaa! This is awesome!

It looks like there are differences in the outputs between the previously passing commit and the newest commit stemming from as early as PCA. Moreover, from what I can tell you reverted all your changes since dc2c91a, so I have to agree: I don't think this error is at all based on what you've done!

I'll try and dig into this with the other maintainers over the next few days to see if we can come up with the source of the discrepancy and ping you if we have any questions. Otherwise, we'll try and get this reviewed and merged ASAP. Thank you again, and happy Hacktoberfest!

**Comment by emdupre** [comment]
Thanks so much for fixing this merge conflict, @frodeaa !!! I'm sorry for introducing it in the first place :disappointed: 

It looks like this is ready to merge, now, but let me know if you're still working on it !

**Comment by frodeaa** [comment]
No problem, I'm done.

@rmarkello did you find out the reason why the "integration" test broke?

**Comment by rmarkello** [comment]
Hey @frodeaa! This all looks awesome :raised_hands: 

Unfortunately I wasn't able to figure out the reason for the break. I've dug through the logs to compare dependency versions, etc, but can't find anything that would explain it. 

I think the plan, at least from the discussion on Gitter, is to accept the failure and use this as an opportunity to introduce some changes that were going to break integration tests, anyway. Thankfully, that means this can finally be merged!

**Comment by emdupre** [comment]
Hi @frodeaa !

Great, thank you so much again for an excellent contribution !! :jack_o_lantern: :tada: 

Just to give a bit more context to @rmarkello's answer, we had a meeting to decide on some pretty major changes in relation to the roadmap -- you can see [minutes from the meeting here](https://docs.google.com/document/d/1fSiBnjaM2XIejgIJDOYHfUcEXUJnst2dKuV3aU6zjNE/edit?usp=sharing).

The outcome, as Ross said, was to go ahead and allow for breaking changes since we're going to finally finish #119 and #44, which are both pretty major ones. After that, we're back to business as usual (i.e., requiring passing integration tests).  If you'd like to give feedback on the roadmap, please do ! We have it open for comments in #151.

Hope to see you around, and thanks so much again for the work you've put into this !

**Pull request merged**
