### PR TITLE
[DOC] Adds NIMH CMN video

### LINKED ISSUE #791: Add CMN Presentation on Multi-Echo fMRI to Resources on readthedocs
### Summary
I'd like to add an [NIMH Center for Multimodal Neuroimaging](https://youtu.be/G1Ftd2IwF14) video on the benefits of multi-echo to our site's resources page.

### Next Steps
- [ ] Open PR

### PR DESCRIPTION
**Pull request by jbteves**
Closes #791  .

Changes proposed in this pull request:

- Adds CMN video to resources
-

### CODE REVIEW

**Comment by tsalo** [comment]
Just curious, but do you know why comments are turned off?

**Comment by jbteves** [comment]
Truly excessive levels of spam.

**Comment by tsalo** [comment]
That's unfortunate. I suppose there are better venues for discussing the content of the video anyway.

**Comment by tsalo** [comment]
Regarding the actual PR, it looks like there's an extra bit of whitespace in the list:

image

**Review by tsalo — APPROVED** [review]
The whitespace thing isn't a real blocker, so I'm approving.

**Review by handwerkerd — APPROVED** [review]
I could only handle listening to the last speaker for a short while, but otherwise good.

**Review by eurunuela — APPROVED** [review]
LGTM!

**Pull request merged**
