### PR TITLE
Create a GitHub Action to automatically add issues to projects

### PR DESCRIPTION
**Pull request by eurunuela**
Closes none.

Changes proposed in this pull request:

- Creates a GitHub Action that adds issues to the documentation and datasets project boards we have, if they have the `documentation` and `dataset` tags respectively.
- I cannot add the secret key to this repository, so someone with admin permissions will have to do it.

### CODE REVIEW

**Comment by eurunuela** [comment]
Would you like to try this @handwerkerd @tsalo ? Feel free to close the PR if you'd rather manually update the boards.

**Review by tsalo — APPROVED** [review]
I think we'll need to merge before we can test it.

BTW do you know if there's any way to automatically label incoming issues as TODO in the relevant project?

**Comment by tsalo** [comment]
Ah, oh well. Setting the issues as "TODO" can be something we tackle at a later date.

**Comment by eurunuela** [comment]
> Ah, oh well. Setting the issues as "TODO" can be something we tackle at a later date.

Oh, that's not what I meant. I thank if the project has a kanban board with a column called "todo", we could just use the option `column` and set it to `column: TODO`.

**Comment by handwerkerd** [comment]
I'm fine trying this but I'm still thinking about how we'll use the board in practice. As an example, I guess this would automatically put all `documentation` labelled issues into one project, which wouldn't have value added beyond just searching for issues with the `documentation` label unless we use that project to organize the open issues (which would be useful to do).

From @tsalo's comment, we already have `priority` `effort` and `impact` labels` that could potentially be used to automatically sort issues on the projects into some type of TODO. For `documentation` the bigger organization that would help me would be for "tedana execution documentation" vs "tedana explanation of the method" vs "multi-echo education." We could make labels for those, but that might be a good way to manually(?) organize issues in a project.

All that said, if @tsalo is fine adding a secret key to the repo and approving this, I'm also fine giving it a try.

**Review by handwerkerd — APPROVED** [review]

**Comment by eurunuela** [comment]
@tsalo could you please merge this when you've added the secret key? Thanks!

**Comment by tsalo** [comment]
@eurunuela sorry I missed Dan's comment from earlier this week. I just bumped up your role in the org so you should be able to add the secret key now.

**Comment by eurunuela** [comment]
> @eurunuela sorry I missed Dan's comment from earlier this week. I just bumped up your role in the org so you should be able to add the secret key now.

Thank you! I'll add the key and merge then.

**Comment by eurunuela** [comment]
I'm closing this as it looks like I was able to automate the process through the _workflows_ menu of each project.

**Pull request closed without merging**
