### PR TITLE
[FIX] Add quiet and debug options to t2smap

### PR DESCRIPTION
**Pull request by emdupre**
Changes proposed in this pull request:

- **HOTFIX !** Adds missing arguments to `t2smap`. 
- This was previously unnoticed since the `t2smap` workflow was only called in the context of the `tedana` workflow

### CODE REVIEW

**Comment by emdupre** [comment]
Merging for https://github.com/poldracklab/fmriprep/pull/1263, unless @tsalo has any objections !

**Comment by tsalo** [comment]
Do `debug` and `quiet` need to be popped out of `options` before they're fed into `t2smap_workflow` or will it work as is?

**Comment by emdupre** [comment]
Sorry, could you confirm what you mean by "popped out" ? I'm not sure I'm following..

**Comment by tsalo** [comment]
I just meant that they might need to be removed from the `options` dictionary somehow before being fed into `t2smap_workflow`. Or maybe they could be added as arguments to `t2smap_workflow`?

**Comment by emdupre** [comment]
Oh I see, thanks ! Yes, you're right, I'll change this.

**Comment by emdupre** [comment]
OK, I think this is fixed. I'll merge and try moving forward with the fmriprep PR pinned to this commit !

**Comment by emdupre** [comment]
@all-contributors add @tsalo for reviewing pull requests, please ?

**Comment by emdupre** [comment]
@all-contributors add @tsalo for pull requests review, please ?

**Pull request merged**
