### PR TITLE
[FIX] Normalize PCA mixing matrix over time, not component

### PR DESCRIPTION
**Pull request by tsalo**
References #223.  One of the concerns I brought up in #223 is that the normalized PCA mixing matrix, which is only used to calculate the weight maps (`WTS`) within `fitmodels_direct`, is normalized over component, rather than over time. This strikes me as invalid, though I could be misinterpreting the purpose of the normalization. This will not impact the MLE dimensionality estimation, but should improve the validity of the Kundu PCA decision tree.

Changes proposed in this pull request:

- Z-score the PCA mixing matrix over time (per component), rather than over components (per TR).

### CODE REVIEW

**Comment by tsalo** [comment]
The first echo in the five-echo dataset (i.e., the one with the highest kappa) is being rejected as a mid-Kappa component. This makes no sense for a couple of reasons:
1. It's the highest Kappa component. It really can't be a mid-Kappa component if it's the highest Kappa component.
2. The proposed change only affects TEDPCA metric calculation. Since this test uses MLE dimensionality estimation, those metrics _aren't even used_!

**Comment by tsalo** [comment]
My bad. This issue is definitely showing up in `master`, so it's not linked to the proposed changes.

**Comment by emdupre** [comment]
To the best of my understanding, the purpose of normalization was so that each components would be on the same scale when passed on to the PCA decision tree (and therefore could use e.g. the same thresholds). If we normalize by time, that assumption no longer holds. 

Could you explain a little more why you were thinking it would make sense to normalize over time ?

**Comment by tsalo** [comment]
The old way was z-scoring each timepoint across components, while this fix z-scores each component across timepoints. The former approach doesn't just rescale the time series, but also changes them. Granted, the difference is small (the correlation for a random array with 80 components and 160 timepoints before vs. after z-scoring is ~0.99), but it should also not be a valid change to make, as far as I can tell.

**Comment by emdupre** [comment]
Ah, sorry, I think I misunderstood ! So to clarify (for me):

What is the correlation between the original components and this new normalization ? The 0.99 is with the old normalization, correct ?

I think we should be checking the PCA selection tree in the integration tests. This seems like as good a time as any, since I want to know how this is impacting the PCA selection. WDYT ? Should we add it to the three echo dataset ?

**Comment by tsalo** [comment]
The time series correlate perfectly after z-scoring the new way. Yeah, the old way gets 0.999.

That's a good idea. I can change the three-echo integration test in this PR.

**Comment by emdupre** [comment]
If this is correlating at 1.0 then I'm wondering if it's really a necessary normalization -- obviously removing the old one seems to be !

If we can fix the merge conflict (sorry, I think I pulled it in with #208 ) then this LGTM !

**Comment by tsalo** [comment]
It's used to generate the normalized version of the mixing matrix, which is used in `fitmodels_direct`. Hypothetically, the scale of the time series should impact the parameter estimates, and I believe that the goal of the z-scoring is to make the parameter estimates from `computefeats2` equivalent to betas. This is definitely something worth discussing in the larger context of how metric calculation should be performed (e.g., in #178, #179, and #223), but if we work under the assumption that the current version of `fitmodels_direct` is generally correct, then this is still a bug that needs to be fixed.

**Comment by emdupre** [comment]
I think this is good to merge. It sounds like we need to do some issue clean-up around metric calculation -- we can deal with that after this is in :)

**Pull request merged**
