### PR TITLE
[DOC] Use README as long_desc

### LINKED ISSUE #472: Add long description to package metadata
### Summary
We should fill out the [`__longdesc__` field in info.py](https://github.com/ME-ICA/tedana/blob/5e0b3eefddfe751a0964b048bb4389d066028e28/tedana/info.py#L24), which currently just says "To do". This really only affects tedana's documentation on [PyPi](https://pypi.org/project/tedana/).

### Next Steps
1. Add a description to the file. The PyPi page will look good after the next release.

### PR DESCRIPTION
**Pull request by emdupre**
Closes #472.

Changes proposed in this pull request:

- Uses the README text as the package "long description," which currently reads as "To do."
- The long description can be [seen on PyPi here](https://pypi.org/project/tedana/).

### CODE REVIEW

**Comment by tsalo** [comment]
> Closes None 😞

Nonsense. It closes #472!

**Comment by tsalo** [comment]
Does the README need to be in the manifest file or anything for this to work for the deployed package?

**Comment by emdupre** [comment]
I don't think so. I'm basing this idea off of Jupyter Book, and [their manifest](https://github.com/executablebooks/jupyter-book/blob/master/MANIFEST.in) doesn't include their README !

**Comment by emdupre** [comment]
Thanks, everyone ! Merging :rocket:

**Pull request merged**
