### PR TITLE
[TST] New smoke tests for functions in decay.py 

### PR DESCRIPTION
**Pull request by monicayao**
Addresses part of #335

Changes proposed in this pull request:

- Added smoke tests for `fit_decay` and `fit_decay_ts` 
- Both tests are fashioned in the style of `test_smoke_kundu_metrics` from [test_model_kundu_metrics.py](https://github.com/ME-ICA/tedana/blob/master/tedana/tests/test_model_kundu_metrics.py)
- Question for the new tests - should I check the size of the outputs, or is that outside the scope of a smoke test?

### CODE REVIEW

**Comment by monicayao** [comment]
> Generally very good. Small technical point that I’d like corrected: the numbers generated are ints, not bools. In Python they can be casted to bool implicitly but the type of the matrix is still int.

@jbteves ah yes! I was aware of this but since 0 and 1s have the same effect as false and trues I thought it would be fine to do this and add a comment to explain it. 

Since it is called from the line `data = data[mask]` in `decay.py`, the effects are the same. Should I still change this?

**Comment by jbteves** [comment]
Oh, I just want the comment to not say bool, you don’t have to change the test. The most common descriptor is probably “binary mask.”

**Comment by tsalo** [comment]
@monicayao Is there anything else you wanted to do here or is this ready to merge?

**Comment by tsalo** [comment]
Can you pull from master to run the new testing setup?

**Comment by monicayao** [comment]
@tsalo Hi! I think this is ready to merge. I do want to make the random inputs a pytest fixture eventually, but I think that can come after writing the more important test functions first. I updated my branch from master, and everything ran as before. 🎉

**Pull request merged**
