### PR TITLE
Rename sphinx functions to fix building error for docs

### LINKED ISSUE #726: Docs fail to build
### Summary
As of this week, it seems like `sphinx` got updated and a couple of functions we use have been renamed, hence the errors.

### Next Steps
Rename the two functions as I did for phys2bids [here](https://github.com/physiopy/phys2bids/pull/399).

### PR DESCRIPTION
**Pull request by eurunuela**
Closes #726 .

Changes proposed in this pull request:

- Renames two `sphinx` functions that have been renamed (probably after an update).

### CODE REVIEW

**Comment by jbteves** [comment]
@eurunuela do you mind sending a patch where you don't auto-format so we can see changes only related to build? Though it looks like pretty much everyone is using `black` at this point, so might be worth discussing on Friday.

**Comment by eurunuela** [comment]
I'm sorry about that @jbteves . I've started using emacs and I've got it set up so that it automatically formats in black when I save the file. I'll make the changes!

Re Friday: I'm not sure I'll make it.

**Comment by eurunuela** [comment]
You should only see non-style changes now @jbteves . Thanks for pointing it out!

**Review by jbteves — APPROVED** [review]
LGTM, thanks @eurunuela !

**Review by handwerkerd — APPROVED** [review]

**Pull request merged**
