### PR TITLE
Improve component plots

### LINKED ISSUE #1042: Check orientation of brain/acquisition in figures
check orientation of brain/acquisition when making multiplanar cuts - rotate to normal. 

Sometimes with R-L acquisitions the brain is flipped on its side, coronal isn't coronal, etc - That just adds a bit of frustration (and possible confusion) when inspecting output. May be an easy fix...

_Originally posted by @dowdlelt in https://github.com/ME-ICA/tedana/issues/383#issuecomment-535113411_

### PR DESCRIPTION
**Pull request by tsalo**
Closes #1042.

Changes proposed in this pull request:

- Use `plot_stat_map` instead of identifying and plotting individual slices. This should address the potential orientation issues from #1042. It will also select the "best" slices for each component independently, so different components will have different slices rendered.

### CODE REVIEW

**Comment by tsalo** [comment]
Argh, tight_layout doesn't help the line plots, but using `plot_stat_map` should fix any orientation issues.

**Comment by tsalo** [comment]
Here's what an example component figure looks like:

image

**Review by handwerkerd — COMMENTED** [review]
This looks much better. One thing I noticed is that the presented slices vary by component. For example, for the three-echo integration test, here are the images for components 15 & 51. The axial slice numbers are different. This is not great because we really want to compare the component maps between components, but I don't see an obvious way to fix this within `plot_stat_map`. Thoughts?
image
image

**Comment by tsalo** [comment]
`plot_stat_map` will identify the "best" slices to present (probably the ones with the highest values, given a certain amount of space between slices). I think that would be better for getting a sense of the component's spatial pattern than being able to directly compare across components.

**Review by handwerkerd — APPROVED** [review]
LGTM

So that we remember this change, note that the presented slices may be different for each component in the opening comment for this PR.

**Comment by tsalo** [comment]
Done!

**Review by dowdlelt — APPROVED** [review]
I'm sad to see the originals go - but happy with similarly oriented brains. 

I'm of two minds about the "best slices" approach - because it is nice to flip between components and see how the structure changes in the same area....but I'm convinced enough that it is better to have a better grasp of the individual components.

I think, based on what I've seen, that there is still enough information there to identify good/bad components, and perhaps it can do even better. Not worth holding up the overall fix, and potentially it could even improve that process.

**Pull request merged**
