### PR TITLE
[REF] Replace duecredit with BibTeX

### LINKED ISSUE #873: Enhance reports with BibTeX citations
### Summary

Per today's call, we probably will be dropping duecredit soon. In the interest of making our reports as useful as possible (especially in the absence of references from duecredit), we should probably enhance our boilerplates with BibTeX references.

### Additional Detail

Two elements that would be great are:
- A single BibTeX file that is simply referenced throughout the library.
- Rendering the BibTeX references in the HTML report.

### Next Steps

1. Compile a full list of references. Not just the ones in tedana, but also references for any dependencies we can think of.
1. We may need to reach out to nipreps and/or pybids-reports 2.0 folks to see if there is a pre-existing solution.

### PR DESCRIPTION
**Pull request by tsalo**
Closes #873.

Changes proposed in this pull request:

- Remove `duecredit` as a dependency and remove all due decorators.
- Remove the `RefLGR` and have BibTeX citations in the `RepLGR` strings.
    - ~~We still need to figure out how to load the references BibTeX file, select the references that are actually used in the report string, and output those to the report.~~ Done!
- Add references.bib BibTeX file.
- Use sphinxcontrib-bibtex for docstring references.
    - We can also use this throughout the documentation, outside of docstrings!

### CODE REVIEW

**Comment by tsalo** [comment]
@eurunuela this PR is now ready for review, if you have the time for it.

**Review by eurunuela — APPROVED** [review]
This is great. Thank you @tsalo!

I built the docs on my computer and the references look perfect.

I guess my only question is regarding GitHub's supported citations. Is that something we have to do once the PR is merged?

**Comment by tsalo** [comment]
Sorry, what do you mean by "GitHub's supported citations"? Do you mean the "Cite this repository" option available when repositories have a CFF file?

**Comment by eurunuela** [comment]
> Sorry, what do you mean by "GitHub's supported citations"? Do you mean the "Cite this repository" option available when repositories have a CFF file?

Sorry, yes. That's what I was referring to.

**Comment by tsalo** [comment]
We can tackle that in a separate PR. We can add the CFF file with the JOSS paper citation, but I'm still concerned about getting folks to cite individual releases' Zenodo DOIs. The two problems are (1) CFF can support multiple citations, but will only show one of them to users on GitHub, and (2) the Zenodo DOI is minted _after_ the release is made, so any code _in_ tedana will only reflect the previous release.

This PR doesn't address the second problem, but it does let us put as many references as we want in the reports (as we already do), so we _could_ have both the JOSS and Zenodo citations in the boilerplate.

**Comment by dowdlelt** [comment]
I haven't had a chance to do an in depth look at this so maybe I'm completely missing the mark...but before I forget: I looked at the docs generated for this PR and `duecredit` is mentioned right at the beginning under the Citation heading as well as in the Installation section. Should reference to duecredit be removed there (it is also in the FAQ section, but that may be wise if someone is encountering `duecredit` in an older version).

**Comment by tsalo** [comment]
I forgot about the docs. Thanks for catching that! I've removed all mentions of duecredit.

**Comment by eurunuela** [comment]
Good catch @dowdlelt! I missed it too.

**Comment by jbteves** [comment]
This looks good, but could we move all of the bibtex utils into a new file, perhaps `bibtex.py`? I just feel like it will be difficult to figure out how they're distinct from other utilities with the current names, and there's several of them so it makes sense to split them off.

**Comment by tsalo** [comment]
@jbteves that's a great idea. I think everything should now be sufficiently separated.

**Comment by jbteves** [comment]
I'm biased because it's my idea but looks good to me 😉

**Review by jbteves — APPROVED** [review]

**Review by eurunuela — APPROVED** [review]
LGTM! Thank you @tsalo

**Comment by tsalo** [comment]
Thanks all! Merging now.

**Pull request merged**
