### PR TITLE
[TST] Expands integration

### PR DESCRIPTION
**Pull request by jbteves**
Closes None

Changes proposed in this pull request:

- Adds four-echo integration test
- Renames integration outputs files

### CODE REVIEW

**Comment by jbteves** [comment]
@rmarkello looks like I had double tapped your name yesterday, sorry about that. I *do* in fact want your review.

**Comment by tsalo** [comment]
The tests are failing because they're using TEDPCA options only available in the maPCA branch. I don't know if you want to wait until that PR is merged to review this or if you want to get it reviewed now and change the parameters later.

**Comment by jbteves** [comment]
Wrong button, ack, I'd rather get it reviewed now because it's identical to the now-closed #471 except in a new branch. Just want to make sure I didn't botch that.

**Comment by tsalo** [comment]
I'm happy to review it now (if it hasn't changed then it should be fine), but I'd prefer to have this PR as a draft if it can't be merged until #435 is handled. Just so that it can't be accidentally merged somehow.

**Comment by jbteves** [comment]
The only way to open as a draft is to close and open a new one. It shouldn't get merged unless mapca is, too, because otherwise the tests will fail since the options won't exist. But if you'd still prefer I do that I can.

**Comment by jbteves** [comment]
Sorry folks, forgot that pushing the merge conflict commit would make your reviews stale.

**Comment by tsalo** [comment]
Something's wrong with the coverage report, [from CircleCI](https://circleci.com/gh/ME-ICA/tedana/8048?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link):

> HTTP 400
> Commit sha does not match Circle build.
> Codecov upload failed

**Comment by jbteves** [comment]
It seems this is a bug in [codecov-bash](https://github.com/codecov/codecov-bash/issues/134). I'll have to push an empty commit.

**Comment by jbteves** [comment]
Okay, I think we're all set now @tsalo @rmarkello, sorry again for having you re-review.

**Comment by jbteves** [comment]
As a separate issue, we should probably remove coverage on the /tests/ directory

**Comment by eurunuela** [comment]
Great to see this is finished too! 🤘🏻

**Comment by tsalo** [comment]
Closes #444.

**Pull request merged**
