### PR TITLE
Update acquisition.rst to include information for Philips scanners

### PR DESCRIPTION
**Pull request by mjversluis**
Include description for Philips users

Closes # .

Changes proposed in this pull request:
add availability of ME-EPI sequences on Philips scanners
-
-

### CODE REVIEW

**Comment by jbteves** [comment]
Thanks for your pull request @mjversluis ! Would you mind adding more information about which software versions allow the multi-echo sequences, or how to obtain them? Just a sentence or two would be useful.

**Comment by jbteves** [comment]
Thanks @mjversluis ! Is there a sample sequence that you can recommend?

**Comment by mjversluis** [comment]
> Thanks @mjversluis ! Is there a sample sequence that you can recommend?

Well, that is difficult to say, because it is so user dependent. What I could do is recommend a starting point, would that be helpful? I am a bit in doubt because of the flexibility and differences in user needs (e..g TRs, number of echoes, resolution) and hardware (Multiband presence, gradient performance).

**Comment by jbteves** [comment]
Yes, a starting point would be amazing!

**Comment by jbteves** [comment]
@all-contributors add @mjversluis for documentation.

**Comment by jbteves** [comment]
Closes #581

**Comment by jbteves** [comment]
Thanks so much for your contribution @mjversluis ! Merging.

**Pull request merged**
