### PR TITLE
[MAINT] Drop 3.5 support and begin 3.8 and 3.9 support

### LINKED ISSUE #706: End Python 3.5 compatibility
### Summary
Python 3.5 reached end of life in September 2020, however we still unit test for it. I believe we should discuss ending Python 3.5 support as it is now affecting testing in #692. Please 👍🏼 or 👎🏼 this issue to indicate if you support removing 3.5 support in the next release. If not, please indicate your reasoning.

### Next Steps
- [ ] Decide if it is time to end support for 3.5 at the next release
- [ ] Document the drop in support in documentation and release notes
- [ ] Update PYTHON_REQUIRES to 3.6 and above

### PR DESCRIPTION
**Pull request by tsalo**
Closes #706 and #707.

Changes proposed in this pull request:

- Drop support for Python 3.5.
- Remove tests for Python 3.5.
- Add support for Python 3.8 and 3.9.
- Add tests for Python 3.8 and 3.9.

Once this is merged, we'll need to update our required checks under the `main` branch's protection rules.

### CODE REVIEW

**Comment by tsalo** [comment]
I'm not sure if we want to merge this before releasing 0.0.10, but it might be good to have the Python version changes _before_ we make releases with the modularization PRs merged in.

**Comment by jbteves** [comment]
I agree, this should be merged in and released before those.

**Comment by tsalo** [comment]
> Weird, GitHub seems to think that CircleCI needs 3.5 but CircleCI clearly understands that it does not.

That's because `unittest_35` is a required check under our branch protection rules for `main`. We'll probably want to change those before we merge this PR, but preferably after it has the necessary approving reviews, so that other PRs can still be reviewed and merged in the meantime. Once this is merged, we'll want to update all of our pending PRs so that they have the right tests for our branch protection rules ASAP.

**Review by jbteves — DISMISSED** [review]
LGTM, thanks!

**Comment by emdupre** [comment]
I think we also need to update this file in the docs: https://github.com/ME-ICA/tedana/blob/2363b4ffa8babe69c9ad0fa7e90e0da5cfed18be/docs/installation.rst

and the installation section in the README : https://github.com/ME-ICA/tedana/blob/2363b4ffa8babe69c9ad0fa7e90e0da5cfed18be/README.md#installation

!

**Comment by emdupre** [comment]
Also, it looks like the unittest_35 is still being expected for status, but 38 and 39 are not. I don't see where that's set in the dockerfile -- is it something we should be updating on the circle side ?

**Comment by tsalo** [comment]
No it's a branch protection rule, so it's something we need to change for the repository itself. My current plan is to update our rules after this PR has two approvals, but before we merge. Then we'll need to update all of the other PRs.

**Comment by emdupre** [comment]
Clearly I can't read 😬 Since you've already explained that above ! Sorry for the noise.

**Review by emdupre — APPROVED** [review]

**Comment by tsalo** [comment]
I think @jbteves' approving review can be considered persistent since the only changes I made _after_ the review were to the README files. Merging now.

**Pull request merged**
