### PR TITLE
[MAINT] Modifies actions to run on release publish

### PR DESCRIPTION
**Pull request by jbteves**
Closes None

Changes proposed in this pull request:

- Modifies GitHub Actions to upload to PyPI on release *publish* specifically
-

### CODE REVIEW

**Comment by jbteves** [comment]
Per discussion on StackOverflow, courtesy of @emdupre:
https://stackoverflow.com/questions/59319281/github-action-different-between-release-created-and-published/61066906#61066906

However, I'm not sold that this is why our pipeline didn't trigger as I manually made and saved a draft.

**Review by tsalo — APPROVED** [review]
LGTM. I think you'll need to delete the old release and tag and then make a fresh one to trigger this.

**Comment by jbteves** [comment]
@tsalo unfortunately yes. If this persists for another release we should consider adding even more to the dev docs about publishing since it seems pretty finnicky lately.

**Review by emdupre — APPROVED** [review]
Let's try it !

**Comment by jbteves** [comment]
It worked!

**Pull request merged**
