### PR TITLE
[MAINT] Adds duecredit as requirement

### LINKED ISSUE #196: DueCredit not imported
When using a miniconda3 environment or pip install, the following import error occurs:
```
Failed to import duecredit due to No module named 'duecredit'
```
Unless we are avoiding acknowledging the devs and their hard work, we should probably fix that :-)

### PR DESCRIPTION
**Pull request by jbteves**
Closes #196 .

Changes proposed in this pull request:

- Adds duecredit as a dependency
-

### CODE REVIEW

**Comment by tsalo** [comment]
If duecredit is a requirement, I believe we can also remove `due.py`, since it is only there to deal with duecredit import issues.

**Comment by tsalo** [comment]
Also, you can remove the `duecredit` requirement group.

**Comment by jbteves** [comment]
The way we have this set up, removing `due.py` actually creates a circular dependency at install... We import from `info.py` to get our requirements, but `info.py` would then require `duecredit`. We could only resolve this by moving the citations elsewhere in the package.

**Comment by tsalo** [comment]
Ah, I see. I think that's a compelling reason for us to switch from `info.py` to `setup.cfg`, but that can be addressed in a separate PR.

**Comment by tsalo** [comment]
In that case, the only other things that need to be done in this PR are:
1. Remove the duecredit dependency group from `info.py`.
2. Potentially add `duecredit` to the list of dependencies in the README. Personally, I don't like duplicating that information outside of the actual dependencies file (i.e., `info.py` or `setup.cfg`), so I won't push for this.
3. Remove the FAQ about the duecredit warning from `docs/faq.rst`.
4. Remove the line about duecredit being an optional dependency from `docs/installation.rst`.

**Comment by jbteves** [comment]
For (1), I'd rather not move that from `info.py` and then lump it in with other changes to the config. Happy to skip adding in (2), and then will push shortly for (3) and (4).

**Review by tsalo — APPROVED** [review]

**Comment by tsalo** [comment]
Since we converged on dropping duecredit entirely, do you want to repurpose this PR or just close it?

**Comment by jbteves** [comment]
We can just close this.

**Pull request closed without merging**
