### PR TITLE
[MAINT] Add new contributors to Zenodo file

### PR DESCRIPTION
**Pull request by tsalo**
Closes None, but stems from #669.

Changes proposed in this pull request:

- Add new contributors to the Zenodo file.

### CODE REVIEW

**Review by jbteves — APPROVED** [review]
LGTM, thanks for handling this @tsalo !
Similar to the #671 I think you'll have to push an empty commit to trigger tests once the DockerHub issue is resolved.

**Review by eurunuela — APPROVED** [review]
LGTM! Thanks!

**Comment by jbteves** [comment]
@tsalo I'm actually a little confused; did you restart the checks on CircleCI or did they somehow auto-restart?

**Comment by tsalo** [comment]
I restarted them. I have the necessary permissions.

**Pull request merged**
